# Generated by Django 5.0.2 on 2024-03-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipies_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recipie_image', models.ImageField(upload_to='recepies')),
            ],
        ),
    ]
